"""add nav_change_pct and all_time_high to etfs

Revision ID: d04657a39abe
Revises: 001
Create Date: 2026-06-10 22:43:35.209008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04657a39abe'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etfs', sa.Column('nav_change_pct', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('etfs', sa.Column('all_time_high', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etfs', 'all_time_high')
    op.drop_column('etfs', 'nav_change_pct')
    # ### end Alembic commands ###
